// <auto-generated />
namespace MVC_SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class scratch_base : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(scratch_base));
        
        string IMigrationMetadata.Id
        {
            get { return "202003041722385_scratch_base"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
