// <auto-generated />
namespace MVC_SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Volume_Datatype_Change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Volume_Datatype_Change));
        
        string IMigrationMetadata.Id
        {
            get { return "202003132031451_Volume_Datatype_Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
